#%RAML 1.0

title: REST-Countries
description: Get information about countries via a RESTful API
baseUri: https://restcountries.eu/rest/v2

mediaType:
    application/json

types:
    Country:
        type: object
        properties:
            name : string
            capital: string
            region: string
            population: number
            latlng: number[]
            currencies: Currency[]
            languages: Language[]
    Currency:
        type: object
        properties:
            code: string
            name: string
            symbol: string
    Language:
        type: object
        properties:
            iso639_1: string
            iso639_2: string
            name: string
            nativeName: string

/all:
    displayName: All Countries
    description: Returns all countries
    get:
        responses:
            200:
                body:
                    type: Country[]

/name:
    /{name}:
        uriParameters:
            name:
                type: string
        displayName: Country by name
        description: Returns all countries with the given name
        get:
            queryParameters:
                fullText?:
                    type: boolean

            responses:
                200:
                    body:
                        type: Country[]

/alpha:
    displayName: Country by ISO code
    description: Returns all countries with the given codes
    get:
        queryParameters:
            codes:
                type: string
